### ISSUE TITLE
Login for mobile

### ISSUE THREAD

**Issue by suprbh** [germTheory/germTheoryWebApp#303]
during signup, if user enters an email that already exists in the database, the case is not handled ... it just pops up an alert message saying "undefined"

**Comment by suprbh** [comment]
POST /api/users/signup 400 33.680 ms - 44
TypeError: First argument needs to be a number, array or string.
    at new Buffer (buffer.js:188:15)
    at base64urlEncode (/Users/sasup/Desktop/supriya/hackreactor/Code/germTheoryWebApp/node_modules/jwt-simple/lib/jwt.js:173:26)
    at Object.jwt_encode [as encode](/Users/sasup/Desktop/supriya/hackreactor/Code/germTheoryWebApp/node_modules/jwt-simple/lib/jwt.js:123:17)
    at null.<anonymous> (/Users/sasup/Desktop/supriya/hackreactor/Code/germTheoryWebApp/server/controllers/authController.js:79:25)
    at tryCatch1 (/Users/sasup/Desktop/supriya/hackreactor/Code/germTheoryWebApp/node_modules/sequelize/node_modules/bluebird/js/main/util.js:43:21)
    at Promise$_callHandler [as _callHandler](/Users/sasup/Desktop/supriya/hackreactor/Code/germTheoryWebApp/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:649:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler](/Users/sasup/Desktop/supriya/hackreactor/Code/germTheoryWebApp/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:663:18)
    at Promise$_settlePromiseAt (/Users/sasup/Desktop/supriya/hackreactor/Code/germTheoryWebApp/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:826:14)
    at Promise._settlePromiseAt (/Users/sasup/Desktop/supriya/hackreactor/Code/germTheoryWebApp/node_modules/sequelize/lib/promise.js:66:18)
    at Promise$_settlePromises [as _settlePromises](/Users/sasup/Desktop/supriya/hackreactor/Code/germTheoryWebApp/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:969:14)
