### ISSUE TITLE
Build error: SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by ryojiosawa** [germTheory/germTheoryWebApp#52]
@suprbh - the build is failing in my localhost, and the error is coming from the following line.  Can you pls fix it asap?

/Users/rosawa/dev/HR/germTheoryWebApp/server/config/dbConfig.js:46
              .inTable('users'));
                               ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/rosawa/dev/HR/germTheoryWebApp/server/locations/locationModel.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

@kmeurer, @jjmerino, @jamesongamble

**Comment by suprbh** [comment]
This is the fix for 7877989 : Syntax error in Knex schema.
