### ISSUE TITLE
BUG: .config/dbCreds.js file not found

### ISSUE THREAD

**Issue by jamesongamble** [germTheory/germTheoryWebApp#61]
Here is the stacktrace:

state changed from starting to crashed
2014-11-05T23:05:38.700780+00:00 heroku[api]: Deploy 8bc673f by jamesongamble@gmail.com
2014-11-05T23:05:38.700780+00:00 heroku[api]: Release v11 created by jamesongamble@gmail.com
2014-11-05T23:05:39.058165+00:00 heroku[web.1]: State changed from crashed to starting
2014-11-05T23:05:41.665660+00:00 heroku[web.1]: Starting process with command `node app.js`
2014-11-05T23:05:43.280214+00:00 app[web.1]:     throw err;
2014-11-05T23:05:43.281840+00:00 app[web.1]: Error: Cannot find module './config/dbCreds.js'
2014-11-05T23:05:43.281850+00:00 app[web.1]:     at Object.<anonymous> (/app/server/server.js:3:15)
2014-11-05T23:05:43.281855+00:00 app[web.1]:     at Module.load (module.js:356:32)
2014-11-05T23:05:43.280216+00:00 app[web.1]:           ^
2014-11-05T23:05:43.281844+00:00 app[web.1]:     at Function.Module._load (module.js:280:25)
2014-11-05T23:05:43.281853+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2014-11-05T23:05:43.281846+00:00 app[web.1]:     at Module.require (module.js:364:17)
2014-11-05T23:05:43.281858+00:00 app[web.1]:     at Module.require (module.js:364:17)
2014-11-05T23:05:43.281849+00:00 app[web.1]:     at require (module.js:380:17)
2014-11-05T23:05:43.281856+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2014-11-05T23:05:43.281843+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:338:15)
2014-11-05T23:05:43.281852+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2014-11-05T23:05:43.279821+00:00 app[web.1]:
2014-11-05T23:05:43.279935+00:00 app[web.1]: module.js:340

**Comment by jamesongamble** [comment]
@suprbh @jjmerino

**Comment by ryojiosawa** [comment]
@suprbh, @jjmerino, @kmeurer - our Heroku app is failing with this error.  Can you guys have a look at this asap?

**Comment by jamesongamble** [comment]
Here is the new stacktrace:

2014-11-05T23:34:40.738807+00:00 heroku[web.1]: Starting process with command `node server/server.js`
2014-11-05T23:34:42.106707+00:00 
app[web.1]: module.js:340
2014-11-05T23:34:42.107715+00:00 app[web.1]:     at Function.Module._load (module.js:280:25)
2014-11-05T23:34:42.107714+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:338:15)
2014-11-05T23:34:42.107717+00:00 app[web.1]:     at Module.require (module.js:364:17)
2014-11-05T23:34:42.101452+00:00 app[web.1]: 
2014-11-05T23:34:42.107096+00:00 app[web.1]:     throw err;
2014-11-05T23:34:42.107720+00:00 app[web.1]:     at module.exports (/app/server/config/middleware.js:25:3)
2014-11-05T23:34:42.107291+00:00 app[web.1]:           ^
2014-11-05T23:34:42.107711+00:00 app[web.1]: Error: Cannot find module '../locations/locationroutes.js'
2014-11-05T23:34:42.107718+00:00 app[web.1]:     at require (module.js:380:17)
2014-11-05T23:34:42.107721+00:00 app[web.1]:     at Object.<anonymous> (/app/server/server.js:14:34)
2014-11-05T23:34:42.107728+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2014-11-05T23:34:42.107725+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2014-11-05T23:34:42.107723+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2014-11-05T23:34:42.107726+00:00 app[web.1]:     at Module.load (module.js:356:32)
2014-11-05T23:34:42.928606+00:00 heroku[web.1]: Process exited with status 8
2014-11-05T23:34:42.940414+00:00 heroku[web.1]: State changed from crashed to starting
2014-11-05T23:34:42.939409+00:00 heroku[web.1]: State changed from starting to crashed
2014-11-05T23:34:45.056360+00:00 heroku[api]: Scale to web=1 by jamesongamble@gmail.com
2014-11-05T23:34:45.488967+00:00 heroku[web.1]: Starting process with command `node server/server.js`
2014-11-05T23:34:46.706445+00:00 app[web.1]: module.js:340
2014-11-05T23:34:46.706760+00:00 app[web.1]:           ^
2014-11-05T23:34:46.706754+00:00 app[web.1]:     throw err;
2014-11-05T23:34:46.707016+00:00 app[web.1]: Error: Cannot find module '../locations/locationroutes.js'
2014-11-05T23:34:46.707020+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:338:15)
2014-11-05T23:34:46.707024+00:00 app[web.1]:     at Module.require (module.js:364:17)
2014-11-05T23:34:46.707022+00:00 app[web.1]:     at Function.Module._load (module.js:280:25)
2014-11-05T23:34:46.707026+00:00 app[web.1]:     at require (module.js:380:17)
2014-11-05T23:34:46.706377+00:00 app[web.1]: 
2014-11-05T23:34:46.707028+00:00 app[web.1]:     at module.exports (/app/server/config/middleware.js:25:3)
2014-11-05T23:34:46.707030+00:00 app[web.1]:     at Object.<anonymous> (/app/server/server.js:14:34)
2014-11-05T23:34:46.707032+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2014-11-05T23:34:46.707034+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2014-11-05T23:34:46.707037+00:00 app[web.1]:     at Module.load (module.js:356:32)
2014-11-05T23:34:46.707039+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2014-11-05T23:34:47.494409+00:00 heroku[web.1]: State changed from starting to crashed
2014-11-05T23:34:47.478909+00:00 heroku[web.1]: Process exited with status 8

**Comment by ryojiosawa** [comment]
This issue has been resolved with 64ce8623a7e90bfc6a3b3e4f8d420aea75d6f779
